general:
  category: general
  language: en
  time_range: null
  engines: null

science:
  category: general
  language: en
  time_range: year
  engines: "google scholar,semantic scholar,crossref"

it:
  category: general
  language: en
  time_range: year
  engines: null

research:
  category: general
  language: en
  time_range: null
  engines: null

recent:
  category: general
  language: en
  time_range: month
  engines: null
